name: Release

on:
  release:
    types: [published]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore optimizerDuck.slnx

      - name: Build
        run: dotnet build optimizerDuck.slnx --configuration Release --no-restore

      - name: Test
        run: dotnet test optimizerDuck.Test/optimizerDuck.Test.csproj --configuration Release --no-restore

      - name: Publish Single
        run: |
          dotnet publish optimizerDuck/optimizerDuck.csproj --nologo /p:PublishProfile=Single
        shell: pwsh

      - name: Get version from tag
        id: get_version
        run: |
          $tag = "${{ github.event.release.tag_name }}"
          $version = $tag -replace '^v', ''
          echo "version=$version" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Rename output file
        run: |
          $version = "${{ steps.get_version.outputs.version }}"
          $source = "optimizerDuck/bin/Release/Single/net10.0/publish/win-x64/optimizerDuck.exe"
          $dest = "optimizerDuck-Windows-x64-$version.exe"
          Move-Item -Path $source -Destination $dest
        shell: pwsh

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v3
        with:
          files: ./optimizerDuck-Windows-x64-${{ steps.get_version.outputs.version }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
